import Layout from '@/components/Layout';
import Head from 'next/head';
import Image from 'next/image';
import profilePic from '../../public/images/profile/ak.jpg';
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';
import HireMe from '@/components/HireMe';
import lightBuld from '../../public/images/svgs/miscellaneous_icons_1.svg';
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full h-min dark:bg-dark dark:text-light pt-0">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className=" flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full flex justify-start mr-10 items-center ">
              <Image
                src={profilePic}
                alt="Ahmed"
                className="w-full h-auto  md:inline-block md:mb-8 md:w-full rounded-3xl "
                priority
                sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw, 50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center ">
              <AnimatedText
                text="Turning Vision Into Reality With Code And Design. "
                className="!text-6xl xl:text-5xl lg:!text-center md:text-5xl sm:!text-3xl"
              />
              <p className="my-4 text-base font-medium">
                As a skilled front-end developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development.
              </p>
              <div className="flex items-center self-start lg:self-center lg:gap-6">
                <Link
                  className=" mt-2 bg-dark text-light px-4 py-3
                  rounded-lg text-lg font-semibold hover:bg-light
                  hover:text-dark border flex flex-row
                  border-solid border-transparent
                  hover:border-dark dark:border-light
                   dark:p-4
                   "
                  href="/dummy.pdf"
                  target={'_blank'}
                  download={true}
                >
                  Resume
                  <LinkArrow className={'w-6 ml-1 '} />
                </Link>
                <Link
                  className="ml-4 text-lg font-medium
                   capitalize text-dark dark:text-light underline"
                  href="mailto: ahmed.khaled01233@gamil.com"
                >
                  contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className="absolute right-8 bottom-8 inline-block w-24 md:hidden">
          <Image
            src={lightBuld}
            alt=" Ahmed Khaled"
            className="w-full h-auto"
          />
        </div>
      </main>
    </>
  );
}
